version: 2.1

orbs:
      codecov: codecov/codecov@1.0.5

aliases:
  - &docker
    - image : circleci/python:3.6.4
jobs:
  check-flake8:
    docker: *docker
    steps:
      - run:
          name: Installing flake8
          command: 'sudo pip install flake8'
      - checkout
      - run:
          name: Checking for flake8 errors
          command: 'flake8 '

  build-status:
    docker: *docker
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: 'sudo python setup.py install'
      - run:
          name: Make migrations
          command: 'python manage.py makemigrations'
      - run:
          name: Migrate
          command: 'python manage.py migrate'
      - run:
          name: Build
          command: 'python manage.py check'

  testing-CodeCov:
    docker: *docker
    steps:
        - checkout
        - run:
            name: Installing CodeCov
            command: 'sudo pip install codecov'
        - run:
            name: Installing Dependencies
            command: 'sudo python setup.py install'
        - run:
            name: Make migrations
            command: 'python manage.py makemigrations'
        - run:
            name: Migrate
            command: 'python manage.py migrate'
        - run:
            name: Test and coverage
            command: 'coverage run --source="smfhcp.views,smfhcp.utils" manage.py test smfhcp.test'
        - run:
            name: CLI Report
            command: 'coverage report'
        - store_artifacts:
            path: coverage
        - codecov/upload:
            file: ./coverage/*.json

workflows:
  version: 2.1
  build:
    jobs:
      - check-flake8
      - build-status
      - testing-CodeCov :
          requires:
            - build-status
